# Logitech Extreme Pro X3D controller
teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
        offset: 0.0
      -
        axis: 0 
        target: angular.z
        scale: 1.0
        offset: 0.0
